### PR TITLE
Created and cleaned up the self-modify project

### PR DESCRIPTION
**Pull request by zachbe**
It doesn't work as desired for now, but maybe people can help!

### CODE REVIEW

**Comment by zachbe** [comment]
This now works, kinda. `example_fun_noblocks` runs as desired. It's messy and has missing functionality, but it gets what I'm going for across enough for others to meaningfully contribute.

**Review by JustinCWeiler — APPROVED** [review]
bruh this library stinky trash smh

**Review by PrathamSoni — APPROVED** [review]
nice :)

**Comment by NDevanathan** [comment]
bAd CoDiNG PrAcTIceS
I didn't see enough multi-paragraph comments
I'm gonna have to give this one a check minus on style

**Comment by saligrama** [comment]
Chris says sadge
________________________________

**Comment by saligrama** [comment]
Chris says sadge

**Pull request merged**
